In [1]:
import torch
from torch import nn
import timm
import config as CFG

from torch_geometric.nn import SAGEConv
from transformers import RobertaModel
from utils import LABELS
import torch.nn.functional as F
import random
import warnings
warnings.filterwarnings("ignore")

In [48]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
input = torch.randn(5, 2, requires_grad=True)

In [54]:
target = torch.tensor([1, 0, 1, 0, 1])

In [55]:
out = m(input)

In [56]:
input

tensor([[ 0.9301, -0.0999],
        [-0.3220,  1.0859],
        [-0.2538,  0.4721],
        [-0.6870,  1.6133],
        [-0.5977, -0.0273]], requires_grad=True)

In [57]:
out.T

tensor([[-0.3053, -1.6268, -1.1206, -2.3958, -1.0184],
        [-1.3353, -0.2189, -0.3947, -0.0955, -0.4481]],
       grad_fn=<PermuteBackward>)

In [58]:
output = loss(m(input), target)

In [47]:
input
output

tensor(2.3838, grad_fn=<NllLossBackward>)

In [55]:
image_embedding = torch.randn(2, 5)
graph_embedding = torch.randn(2, 5)

In [56]:
image_embedding[0]

tensor([-0.4353,  2.2675,  1.0529, -0.6233, -2.0594])

In [57]:
torch.tensor(0, dtype=torch.long)


tensor(0)

In [99]:
x = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0]

# get positive of x where x is 1
x_pos = [i for i, v in enumerate(x) if v == 1]

In [114]:
x_pos
#  convert x_post to tensor
x_pos = torch.tensor(x_pos, dtype=torch.long).cuda()

In [115]:
y = [10, 18, 18, 18]
# conver y to tensor
y = torch.tensor(y, dtype=torch.long).cuda()

In [112]:
from sklearn.metrics import accuracy_score

In [118]:
accuracy_score(x_pos.cpu(), y.cpu())

0.25

In [73]:
# random matrix 2x2
A = torch.randn(3, 5)
# random matrix 3x3
B = torch.randn(6, 5)

In [75]:
A

tensor([[-0.4596, -1.6733,  1.7742,  0.9053,  0.2375],
        [-0.7794, -0.2955,  1.0190, -1.0368, -1.5316],
        [ 0.6903,  1.2476,  0.3794,  1.5319, -0.6791]])

In [76]:
B

tensor([[-0.3462, -1.0103,  1.4079, -0.8000,  0.3606],
        [-0.1920,  1.3527, -0.1298, -0.2762, -1.9897],
        [ 0.1508, -0.4221, -0.5237, -0.1070, -0.0967],
        [ 0.2468,  0.5664,  0.2526,  0.0738,  0.3190],
        [-0.5012,  0.7231, -0.1293,  1.7041,  0.1819],
        [ 0.5433,  0.7575,  1.2950, -0.0933, -0.8650]])

In [77]:
logits = A @ B.T

In [78]:
logits.shape

torch.Size([3, 6])

In [80]:
C = torch.randn(3, 5)

In [81]:
C

tensor([[-1.0046,  0.3162,  1.0285, -0.6891,  0.4247],
        [ 0.2987,  0.8883,  1.2372, -0.8184,  0.9563],
        [ 0.2674, -0.2830, -1.0012, -0.7581,  0.2187]])

In [86]:
A_similarity = A @ A.T # 3x3
B_similarity = B @ B.T # 6x6

In [90]:
B_similarity = torch.randn(3, 6)

In [92]:
A_similarity * B_similarity

RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1

In [89]:
logits.shape

torch.Size([3, 6])

In [71]:
# write cross_entropy function
def cross_entropy(targets, logits):
    log_softmax = nn.LogSoftmax(dim=-1)
    loss = (-targets * log_softmax(logits)).sum(1)

In [72]:
cross_entropy(A, B)

IndexError: tensors used as indices must be long, byte or bool tensors

In [3]:
import timm 
import config as CFG
model = timm.create_model(
            CFG.model_name, pretrained=False, num_classes=0, global_pool="avg"
        )

In [4]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act1): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act1): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act2): ReLU(inplace=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act3): ReLU(inplace=True)
      (downsample): Sequen

In [5]:
import torch 
x     = torch.randn(1, 3, 224, 224)


In [6]:
model(x).shape

torch.Size([1, 2048])