In [1]:

import torch
from torch.utils import data
import torchvision
import torchvision.transforms as transforms
import argparse
import os
from model import ImageEncoder
from torch import nn
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit


def inference():
    print('==> Preparing data..')
    # Setting dataset
    transform = transforms.Compose([transforms.Resize((224, 224)),
                                    transforms.ToTensor(),
                                    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])

    img_path = "/mnt/disk1/vaipe-data/pills/result/pill-cropped-211012/"
    data_test = torchvision.datasets.ImageFolder(img_path, transform=transform)
    # data_loader_test = torch.utils.data.DataLoader(data_test, batch_size=16, shuffle=True, num_workers=4)


    # print(data_test.class_to_idx)


if __name__ == "__main__":
    inference()



==> Preparing data..


In [135]:
triplet_loss = nn.TripletMarginWithDistanceLoss(distance_function = nn.CosineSimilarity(dim=-1, eps=1e-6))

In [130]:

anchor = torch.randn(2, 1, 2, requires_grad=True)
positive = torch.randn(2, 1, 2, requires_grad=True)
negative = torch.randn(2, 30, 2, requires_grad=True)

In [136]:
anchor

tensor([[[ 0.2025,  2.1654]],

        [[-0.9019, -1.5008]]], requires_grad=True)

In [137]:
positive

tensor([[[ 2.3643, -0.8047]],

        [[ 0.7060, -0.0375]]], requires_grad=True)

In [138]:
anchor - positive

tensor([[[-2.1617,  2.9701]],

        [[-1.6079, -1.4633]]], grad_fn=<SubBackward0>)

In [139]:
nn.functional.cosine_similarity(anchor, positive)

tensor([[ 1., -1.],
        [-1.,  1.]], grad_fn=<DivBackward0>)

In [121]:
(anchor - positive).shape

torch.Size([2, 1, 128])

In [122]:
(anchor - negative).shape

torch.Size([2, 30, 128])

In [123]:
anchor.shape

torch.Size([2, 1, 128])

In [119]:
output = triplet_loss(anchor, positive, negative)
output

tensor(0.9766, grad_fn=<MeanBackward0>)

In [183]:

input1 = torch.randn(2, 2)
input2 = torch.randn(5, 2)

In [184]:
input1

tensor([[ 1.1745,  0.6011],
        [ 0.2747, -0.4716]])

In [185]:
input1 = input1.unsqueeze(1)

In [186]:
input1

tensor([[[ 1.1745,  0.6011]],

        [[ 0.2747, -0.4716]]])

In [181]:
input1.shape

torch.Size([2, 1, 2])

In [182]:
output = nn.functional.cosine_similarity(input1, input2, dim=-1)
output

tensor([[ 0.9026,  0.8920, -0.7393, -0.2771, -0.9143],
        [ 0.8728,  0.8608, -0.7814, -0.2143, -0.9386]])