In [183]:
from sentence_transformers import SentenceTransformer
from sentence_transformers import losses


In [83]:
model = SentenceTransformer('sentence-transformers/paraphrase-mpnet-base-v2')


In [84]:
# torch cosine 
import torch
cosine = torch.nn.CosineSimilarity(dim=1, eps=1e-08)

In [85]:
sentences = ["Đinh lăng, bạch quả (Hoạt huyết dưỡng não) 150mg+20mg", "Đinh lăng, bạch quả (Hoạt huyết dưỡng não)"]
embeddings = model.encode(sentences)


In [87]:
print(embeddings[0], embeddings[1])

[-1.71422493e-02 -2.58576393e-01  2.03083791e-02  2.29542162e-02
  7.57346451e-02 -2.91245300e-02 -1.96694911e-01 -4.37966734e-02
  4.86471057e-02 -3.43645141e-02 -1.12796582e-01  1.19341336e-01
 -8.16520452e-02  9.33527946e-04  1.72339864e-02 -4.15442027e-02
  2.68769767e-02  8.38556811e-02 -1.48113951e-01 -2.52410900e-02
 -4.68713092e-03 -2.80137751e-02  7.14980438e-02  7.50507638e-02
  1.45838454e-01 -1.50775202e-02 -1.44623881e-02  6.60060048e-02
 -2.29918342e-02 -1.72522709e-01 -4.09753844e-02 -3.53734456e-02
 -1.67952273e-02 -5.13295196e-02 -7.07522547e-03 -1.03866883e-01
  4.04965691e-02  7.63274962e-03 -2.02988222e-01  1.13487139e-01
  3.57379615e-01 -2.22183689e-01 -6.96486086e-02 -4.73471247e-02
 -6.18796609e-02 -6.24677576e-02  1.28823621e-02 -9.08497162e-03
 -6.58090832e-03  2.31774747e-02 -3.10549419e-02  7.51498193e-02
 -1.57330930e-01 -3.42680002e-03  2.25659147e-01 -3.25115949e-01
 -4.28174995e-02  1.73018217e-01  2.51453340e-01 -1.88214157e-03
 -1.78647041e-01  3.11426

In [86]:
# convert embedding to tensor 2D 
embedding_tensor = torch.tensor(embeddings)

# convert embeddings[0] to tensor 2D
embedding_tensor_0 = torch.tensor(embeddings[0])
embedding_tensor_1 = torch.tensor(embeddings[1])

In [80]:
# change embedding_tensor_0 to tensor 2D
embedding_tensor_0 = embedding_tensor_0.unsqueeze(0)
embedding_tensor_1 = embedding_tensor_1.unsqueeze(0)

In [55]:
cosine_similarity = cosine(embedding_tensor_0, embedding_tensor_1)

In [56]:
cosine_similarity 

tensor([0.7549])

In [143]:
class sentencesTransformer(torch.nn.Module):
    def __init__(self, model_name='sentence-transformers/paraphrase-mpnet-base-v2', pretrained=True, trainable=True):
        super().__init__()

        self.model = SentenceTransformer(model_name)
        for param in self.model.parameters():
            param.requires_grad = trainable

    def forward(self, x):
        return self.model.encode(x)

In [144]:
sentencesTra = sentencesTransformer()

In [145]:
sentencesTra(sentences).shape

(2, 768)

In [146]:
array = [['ĐƠN THUỐC BHYT', 'Cân nặng kg', 'Tuổi: 74', 'Mã số thẻ bảo hiểm y tế (nếu có): GD4353520838652', 'Họ tên: TRẦN THỊ NHIỆM', 'Nữ', 'x', 'Chẩn đoán: E11 - Bệnh đái tháo đường không phụ thuộc insuline ; (J40) Viêm', 'Địa chỉ liên hệ: Xã Tiêu Động, Huyện Bình Lục, Tỉnh Hà Nam', 'áp; (G46*) Hội chứng mạch máu não trong bệnh mạch não (I60-I67)', 'phế quản không xác định được là cấp hay mãn tính; (I10) Bệnh lý tăng huyết', 'Thuốc điều trị:', '1) Metformin (Meglucon 1000) 1000 mg', 'Uống: Tối 1 Viên', '2) Gliclazid (Staclazide 30 MR) 30mg', 'SL:30 Viên', 'Uống trước khi ăn : SÁNG 2 Viên', '3) Enalapril (Enalapril) 5mg', 'SL: 60 Viên', 'Uống : SÁNG 1 Viên CHIỀU 1 Viên', '4) Đinh lăng, bạch quả (Hoạt huyết dưỡng não) 150mg+20mg', 'SL: 60 Viên', 'Uống: Sáng 2 viên CHIều 2 viên', 'Lời dặn: Hẹn Khám 7/5/2021', 'SL:40 viên', 'Ngày 06 tháng 04 năm 2021', '(Ký, ghi rõ họ tên)', 'Bác sỹ/Y sỹ khám bệnh', 'Nam', 'Điện thoại:']]

In [147]:
out = sentencesTra(array[0])

In [142]:
out

array([[ 0.08979658, -0.26801896,  0.05210972, ...,  0.03995628,
         0.14682412, -0.00446639],
       [ 0.10245989, -0.07977315, -0.00043534, ..., -0.00341593,
        -0.21482253, -0.15381593],
       [-0.04399467,  0.0897291 , -0.0326392 , ...,  0.13249622,
        -0.0427196 , -0.07870742],
       ...,
       [-0.18267994, -0.42443705,  0.02559022, ...,  0.03667934,
        -0.13268363, -0.07548894],
       [ 0.01113301,  0.07777575, -0.01629597, ..., -0.04879889,
         0.04824065, -0.07516161],
       [ 0.13985889, -0.10641323,  0.04406773, ...,  0.04568093,
         0.0873151 , -0.03129604]], dtype=float32)

In [69]:
tensor = torch.Tensor(out)

In [72]:
tensor

tensor([[ 0.0898, -0.2680,  0.0521,  ...,  0.0400,  0.1468, -0.0045],
        [ 0.1025, -0.0798, -0.0004,  ..., -0.0034, -0.2148, -0.1538],
        [-0.0440,  0.0897, -0.0326,  ...,  0.1325, -0.0427, -0.0787],
        ...,
        [-0.1827, -0.4244,  0.0256,  ...,  0.0367, -0.1327, -0.0755],
        [ 0.0111,  0.0778, -0.0163,  ..., -0.0488,  0.0482, -0.0752],
        [ 0.1399, -0.1064,  0.0441,  ...,  0.0457,  0.0873, -0.0313]])

In [153]:
from transformers import AutoTokenizer, AutoModel
import torch


#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


# Sentences we want sentence embeddings for
sentences = ['TOA THUỐC BHYT', 'Năm sinh1949', 'Họ và tên ĐỖ VĂN HAY', 'Địa chỉ', 'Nam', '208', 'Nữ', 'Chẩn đoán: I10 - Tăng huyết áp vô căn (nguyên phát); (G45) Cơn thiếu máu não thoáng qua và hội', 'C', 'Xã Công Lý - Lý Nhân - Hà Nam', 'Thẻ bảo hiểm y tế', 'HT', 'Mạch:', '2', 'lần/phút', '35', '35', 'Huyết áp:', '/', '17663', 'mmHg', 'Thân nhiệt:', 'Cận lâm sàng:', 'chứng liên quan', '1) NIFEDIPIN T20 STADA RETARD 20 mg', 'SL:32 Viên', 'Sáng 1 Viên', 'SL:20 Viên', 'Uống:', '2) APRATAM 400mg', 'Sáng 1 Viên', 'Ghi chú', 'Ghi chú', 'Ngày 10/10/2019', 'Uống:', 'Cộng khoản: 2 khoản', 'Chiều 1 Viên', '', 'Ngày hẹn tái khám: Thứ hai, 11/11/2019', 'Lời dặn đơn thuốc:', 'Bệnh nhân ký nhận', 'Y, Bác sĩ điều trị']

# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-mpnet-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/paraphrase-mpnet-base-v2')

# Tokenize sentences
encoded_input = tokenizer(sentences, max_length=32, padding='max_length', truncation=True, return_tensors='pt')

# Compute token embeddings
model_output = model(encoded_input['input_ids'], encoded_input['attention_mask'])

# Perform pooling. In this case, max pooling.
sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

print("Sentence embeddings:")
print(sentence_embeddings)

Sentence embeddings:
tensor([[ 0.0176, -0.3601,  0.0144,  ...,  0.0409, -0.0217, -0.0838],
        [-0.1372, -0.1524,  0.0664,  ...,  0.0377, -0.0530, -0.0293],
        [ 0.1309, -0.1451,  0.0101,  ...,  0.1302,  0.1409, -0.0647],
        ...,
        [ 0.1025, -0.0672,  0.0423,  ...,  0.0876,  0.1576, -0.0284],
        [ 0.0328, -0.0788,  0.0906,  ...,  0.0801,  0.0348, -0.0635],
        [ 0.0721, -0.2795,  0.0444,  ...,  0.0899,  0.1432,  0.0156]],
       grad_fn=<DivBackward0>)


In [166]:
model_output

BaseModelOutputWithPooling(last_hidden_state=tensor([[[ 7.9101e-02, -2.6968e-01,  6.6992e-02,  ..., -2.8194e-02,
           9.1040e-02, -4.6519e-02],
         [ 3.1752e-02, -7.8688e-02,  2.6745e-03,  ...,  9.4424e-02,
          -1.1640e-02, -1.1824e-01],
         [ 5.2371e-02, -3.4139e-01,  1.7945e-03,  ...,  1.0887e-01,
           8.5581e-02, -6.6701e-02],
         ...,
         [ 3.0547e-02, -1.0914e-01,  1.3512e-02,  ...,  8.7770e-04,
          -3.2795e-02, -3.6656e-02],
         [ 3.1190e-02, -1.0847e-01,  1.2083e-02,  ...,  6.0462e-04,
          -3.7322e-02, -3.7290e-02],
         [ 2.9984e-02, -1.0650e-01,  1.4542e-02,  ...,  6.2514e-04,
          -3.8165e-02, -3.2939e-02]],

        [[-1.1578e-01, -9.7722e-02,  7.4954e-02,  ..., -3.8370e-02,
          -3.5083e-02, -4.3859e-02],
         [-1.1359e-01, -9.7020e-02,  1.4335e-02,  ...,  1.0089e-01,
          -5.4525e-02, -6.1717e-02],
         [-1.4204e-01, -3.6442e-01,  8.2106e-02,  ...,  6.3074e-02,
          -1.9776e-02, -1.4078e

In [159]:
class sentencesTransformer(torch.nn.Module):
    def __init__(self, model_name='sentence-transformers/paraphrase-mpnet-base-v2', trainable=False):
        super().__init__()

        self.model = AutoModel.from_pretrained(model_name)
        for param in self.model.parameters():
            param.requires_grad = trainable

    def mean_pooling(self, model_output, attention_mask):
        token_embeddings = model_output[0] #First element of model_output contains all token embeddings
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)

    def forward(self, text_sentences_ids, text_sentences_mask):
        model_output = self.model(text_sentences_ids, text_sentences_mask)
        return self.mean_pooling(model_output, text_sentences_mask)

In [160]:
test = sentencesTransformer()

In [165]:
test(encoded_input['input_ids'], encoded_input['attention_mask'])

tensor([[ 0.0176, -0.3601,  0.0144,  ...,  0.0409, -0.0217, -0.0838],
        [-0.1372, -0.1524,  0.0664,  ...,  0.0377, -0.0530, -0.0293],
        [ 0.1309, -0.1451,  0.0101,  ...,  0.1302,  0.1409, -0.0647],
        ...,
        [ 0.1025, -0.0672,  0.0423,  ...,  0.0876,  0.1576, -0.0284],
        [ 0.0328, -0.0788,  0.0906,  ...,  0.0801,  0.0348, -0.0635],
        [ 0.0721, -0.2795,  0.0444,  ...,  0.0899,  0.1432,  0.0156]])

In [162]:
encoded_input['input_ids']

tensor([[    0,  2004,  2054,  ...,     1,     1,     1],
        [    0, 15129,  8258,  ...,     1,     1,     1],
        [    0,  7574, 12440,  ...,     1,     1,     1],
        ...,
        [    0,  8844,  2076,  ...,     1,     1,     1],
        [    0,  3845,  2236,  ...,     1,     1,     1],
        [    0,  1065,  1014,  ...,     1,     1,     1]])

In [164]:
encoded_input['attention_mask'][0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])

False

In [195]:
# create tensor [1,2,23,4]
tensor = torch.Tensor([0, 0, 0, 0])
tensor2 = torch.Tensor([0])

In [197]:
tensor.ne(tensor2)

tensor([False, False, False, False])

In [201]:
sum(tensor[tensor.eq(tensor2)]) == 0

tensor(True)

In [193]:
sum(tensor[tensor.eq(tensor2)])

tensor(1.)

In [181]:
anchor, positive, negative = torch.tensor([]), torch.tensor([]), torch.tensor([])

In [177]:
negative = torch.cat(
            (negative, tensor[tensor.eq(tensor2)].unsqueeze(0)))

In [179]:
len(negative)

1